### ISSUE TITLE
Secret Handshake - All Tests Pass, but Web Editor shows "AN ERROR OCCURRED"

### ISSUE THREAD

**Issue by bushidocodes** [exercism/c#746] opened 2022-01-19 19:24 UTC
BLUF: Possible repeat of regex issue in #736 for "Secret Handshake"

I completed the C track on Exercism 1-2 years ago, and I've been going back to cleanup my solutions and fix anything that might have broken due to subsequent changes to the tests.

I'm seeing the same behavior in #736 for the Secret Handshake problem. After making changes to my solution, all tests seem to pass, but the runner fails, so I can update my previous submission. 

Not sure if the previous solution is still waiting to be deployed or if perhaps this problem was missed in the last pass.

A screenshot is below. Happy to try a fix, but I've only been an Exercism student thus far, so not yet read up on contribution guidelines. I've gained quite a bit from Exercism professionally, so happy to give back if appropriate. 

![image](https://user-images.githubusercontent.com/8700322/150199472-c9db4b62-5bf2-419e-a6b0-9ce4b2531d71.png)

**Comment by wolf99** [comment] 2022-01-20 08:52
Possibly the same issue noted in #744 ?

(In which case a fix is submitted)

**Comment by wolf99** [comment] 2022-01-20 16:31
https://github.com/exercism/c-test-runner/pull/57 was just merged, which should resolve this 🤞.

Can you confirm if the issue is no longer seen? Then this issue could be closed.

**Closed** 2022-01-21 20:18 UTC
