### ISSUE TITLE
tests are passing but it's still treated as error

### ISSUE THREAD

**Issue by ultimastorm** [exercism/c#736] opened 2021-12-18 17:56 UTC
Hi, 
I'm working on the "Saddle Points" exercise. Locally everything runs fine, also online they are reported as passed, but with Error status:

```
We received the following error when we ran your code:

-----------------------
9 Tests 0 Failures 0 Ignored 
OK
```

I can't submit and there is no other information shown about the nature of the error.

Any help or suggestion is appreciated.
Thanks

**Comment by patricksjackson** [comment] 2021-12-18 19:56
Thanks for the report.

The bug is in the [exercism/c-test-runner](https://github.com/exercism/c-test-runner), and is related to how they are detecting the tests. There is a very similar bug here: https://github.com/exercism/c-test-runner/pull/40

It appears that there is a regex used to find the last test name in the file, which is then compared with the test output to make sure all the tests have run. With the linked change above, the regex was fixed to ignore commented out tests.

For `saddle-points`, the last tests were formatted to be on a separate line as the `RUN_TEST` function name, which I'm betting breaks that regex again.
```
int main(void)
{
   UnityBegin("test_saddle_points.c");

   RUN_TEST(test_single_saddle_point);
   RUN_TEST(test_empty_matrix_has_no_saddle_points);
   RUN_TEST(test_lack_of_saddle_points_when_there_are_none);
   RUN_TEST(test_multiple_saddle_points_in_a_column);
   RUN_TEST(test_multiple_saddle_points_in_a_row);
   RUN_TEST(test_saddle_point_in_bottom_right_corner);
   RUN_TEST(test_saddle_points_in_non_square_matrix);
   RUN_TEST(
       test_saddle_points_in_single_column_matrix_are_those_with_the_minimum_value);
   RUN_TEST(
       test_saddle_points_in_single_row_matrix_are_those_with_the_maximum_value);

   return UnityEnd();
}
```

Either the formatting for at least the last test needs to be fixed here so that the test name is on the same line as `RUN_TEST`, or the regex in the c-test-runner needs to be updated again.

**Comment by patricksjackson** [comment] 2021-12-18 20:07
In addition to `saddle-points`, this error also likely affects
`luhn` `crypo-square` `phone-number` `sum-of-multiples` `react` 

(That list may or may not be complete, I just searched with a quick grep)

I confirmed that `luhn` behaves the same in the online editor, though I did not check the others.

I unfortunately don't have the time to address this myself soon, but hopefully someone else can help out.

**Comment by iHiD** [comment] 2021-12-19 18:41
(@ErikSchierboom Tagging you in this in case it's not fixed by the time you get back)

**Comment by siebenschlaefer** [comment] 2021-12-20 00:39
@patricksjackson Where is that regex that detects tests? I can't find it in the c-test-runner.
All I can find is the sed-call that removes `TEST_IGNORE()` calls ([run.sh:42](https://github.com/exercism/c-test-runner/blob/main/bin/run.sh#L42)).

**Comment by wolf99** [comment] 2021-12-20 11:48
Possibly referring to this line ?
https://github.com/exercism/c-test-runner/blob/801f8fd1f97f2dec3ed02061c92b9eddefd660a6/bin/process_results.py#L9

**Comment by siebenschlaefer** [comment] 2021-12-20 16:24
@wolf99 Thanks, I was so focused on the `stdbuf` thing that I missed that regular expression in `process_results.py`.

I think that issue is easy to fix. Currently the RE looks like this:
```py
rgx_testnames = re.compile(r"\n\s*RUN_TEST\(([^)]+)\);")
```
(see [process_results.py:9](https://github.com/exercism/c-test-runner/blob/801f8fd1f97f2dec3ed02061c92b9eddefd660a6/bin/process_results.py#L9))

That captures anything following `"RUN_TEST("`, even spaces and line breaks. E.g. in the phone-number exercise the last test gets called like this:
```c
   RUN_TEST(
       test_invalid_if_exchange_code_starts_with_1_on_valid_11_digit_number);
```
(see [test_phone_number.c:242-243](https://github.com/exercism/c/blob/main/exercises/practice/phone-number/test_phone_number.c#L242-L243)), so `get_last_test_name()` returns
```py
"\n       test_invalid_if_exchange_code_starts_with_1_on_valid_11_digit_number"
```

Then [line 44](https://github.com/exercism/c-test-runner/blob/801f8fd1f97f2dec3ed02061c92b9eddefd660a6/bin/process_results.py#L44) will never `break` and [line 46](https://github.com/exercism/c-test-runner/blob/801f8fd1f97f2dec3ed02061c92b9eddefd660a6/bin/process_results.py#L46) will set the `status` to `"error"`.

But if you match those whitespace characters before the capturing group like this:
```py
rgx_testnames = re.compile(r"\n\s*RUN_TEST\(\s*([^)]+)\);")
```
then `get_last_test_name()` returns the correct name of the last test.

You could even filter out any whitespace characters after the test name:
```py
rgx_testnames = re.compile(r"\n\s*RUN_TEST\(\s*([^)]+?\s*)\);")
```

I'm writing this in detail because I hope somebody else can do the changes and verify their correctness.

(I suck at setting things up. I cloned the test runner into /opt/test-runner and got several issues, e.g. `stdbuf` butchering the output of `make`, `sh` complaining that `"${slug//-/_}"` is not valid in `sh`, when I changed the shell to `bash` I couldn't run `run-in-docker.sh` because there's not `bash`(?)...)

But I did try them and got the right results in two manual tests.

**Comment by ErikSchierboom** [comment] 2022-01-04 12:32
@ultimastorm Could you check if things are now working?

**Closed** 2022-01-04 15:30 UTC
