### ISSUE TITLE
Why not always provide header for client?

### ISSUE THREAD

**Issue by jocal17** [exercism/c#252] opened 2017-12-23 05:18 UTC
How about changing exercise anatomy to
+-- <my exercise>
    +-- makefile
    +-- src
    |   +-- example.c
    |   +-- <my exercise>.h

Since the client always needs to now what the test is expecting, why not either always make them check the test or always have header included? The latter seems better since exercism advertises as beginner friendly.

**Comment by ryanplusplus** [comment] 2017-12-23 14:15
@patricksjackson @wolf99 what are your thoughts? I think we had this discussion before but can't remember why we decided not to provide a header.

**Comment by patricksjackson** [comment] 2017-12-24 03:26
Typically we provide the header if it's the first problem (hello world) or if it's not obvious what the header needs to be from the test file (see the struct definitions in anagram). I would bet that there are at least a couple problems where the necessary header content is really not obvious from the test file though, so just giving all the headers would certainly make things easier.

The problem is we have to walk the line of helping out enough to be 'beginner friendly', yet not taking away too much of the problem solving. If we provided all the headers then we would never be forcing a student to ask "What type should this argument be?". The test files can't always let that be a choice, but we really want students to be asking those questions early, as long as it doesn't turn them off from continuing.

So there is value in learning how to reverse engineer an interface from the test file, and there are several best practices unique to headers that are easier to learn after somebody points them out to you in code review (but you'd probably ignore if we just gave the header). For example, header guards and const'ness in the function definitions.

That said there'd probably be less friction if we just included them all, but that doesn't necessarily mean it'd be better :)

(It's been quite a while since I learned C, so I don't know how prohibitive 'figuring out the headers' actually is, and you can take my opinion with a grain of salt.)

**Comment by wolf99** [comment] 2017-12-24 10:56
Issue #43 discussed this previously. 
For my own opinion, I'd tend to agree with @patricksjackson. As with most language tracks there is a point at which the student has to learn how to implement the interface as well as the implementation. Making the step to deciding on and implementing the header files provides this, at least in part. IMHO people that reach the level where the stub files are no longer provided should be able to figure out how to create them themselves by that point - it is a necessary part of programming in C as only very basic programs could be created without writing one's own header files at some point.

It occurs to me that to for students to experience the full design decision process there should be a some subsequent point at which they are asked to write the test file itself also! AFAICT though this would be unfeasible for the language track infrastructure to handle.

**Comment by wolf99** [comment] 2017-12-24 11:25
I can't recall if the README's provide any hints about this for the first exercises that require it. @jocal17 do you recall which exercise you found this to be an issue?

It might be worth providing some hand-holding for the first one or two. The Java track has done something similar recently, [https://github.com/exercism/java/issues/1075](https://github.com/exercism/java/issues/1075)

**Comment by jocal17** [comment] 2017-12-26 14:59
It was the second exercise, isogram. Since all other exercises I've done provided a starting file my first thought was that the isogram one was broken.

**Comment by wolf99** [comment] 2017-12-27 22:27
Would this have been due to the exercise reordering? Or is it intentional that later exercises provide stubs? (maybe to help in more complex exercises)

**Comment by jocal17** [comment] 2018-01-04 08:22
It was intentional in the other exercises. As far as I can tell they are provided for all exercises. They were Haskell and Python so somewhat different, though Haskell also provides the function types.

**Comment by wolf99** [comment] 2018-01-04 10:23
@jocal17 I kinda meant is it intentional that such an early exercise is left without a header, WRT to ordering in the curriculum. Question is really aimned at @ryanplusplus or @patricksjackson I guess.

**Comment by wolf99** [comment] 2018-01-04 10:36
The current core exercises with stubs, in current order of curriculum is listed below. Later exercises in the list with headers are provided to give type or limit definitions. A number of the non-core exercises also have headers provided. 

Following just the core, IMO it seems the jump to no provided header may now happen a little early in the case that a student is very new to C. Maybe we should provide a header for `isogram` also and a hints.md file for `gigasecond` (and whatever exercises are unlocked by it), to explain that the student is now expected to add the header themselves. What do you think @ryanplusplus , @patricksjackson 

[x] hello-world
[ ] isogram
[ ] gigasecond
[ ] hamming
[ ] grains
[ ] beer-song
[ ] difference-of-squares
[ ] binary-search
[ ] roman-numerals
[x] allergies
[ ] atbash-cipher
[ ] phone-number
[x] clock
[x] sieve
[x] robot-simulator
[ ] pascals-triangle
[ ] binary
[ ] palindrome-products
[ ] scrabble-score
[x] queen-attack

**Comment by ryanplusplus** [comment] 2018-01-04 11:03
I think that sounds reasonable

**Comment by wolf99** [comment] 2018-01-05 11:27
I'll start working on a PR for this soon then 😃

**Comment by wolf99** [comment] 2018-01-08 12:46
Fixed by #255

**Closed by wolf99** 2018-01-08 12:46 UTC
